In [1]:
import torch
import numpy as np

In [4]:
"""
torch.view 정리
1) 원본 데이터와 총 인스턴스 개수는 동일홤
    - 모든 차원을 곱해보면 모두 동일한 값이 나옴
2) 얕은 복사를 지원
    - 변환된 형태를 원본에 저장하고 싶다면 변수에 직접 담아줘야 한다
"""
x = torch.randn(4,4)
x.size, x

(<function Tensor.size>,
 tensor([[ 0.4078, -0.2062, -1.9476, -0.5783],
         [ 0.7319, -0.9079,  0.1607,  1.5403],
         [-1.4357,  0.1099,  0.1589, -0.9753],
         [ 0.8379, -1.7359,  1.1830, -0.0266]]))

In [20]:
"""
1) x.view(-1, 1) => [16, 1]
2) x.view(-1) => [16]
3) x.view(1, -1) => [1, 16]
"""
x.view(-1, 1)
x.view(-1)
x.view(1, -1)

tensor([[ 0.4078, -0.2062, -1.9476, -0.5783,  0.7319, -0.9079,  0.1607,  1.5403,
         -1.4357,  0.1099,  0.1589, -0.9753,  0.8379, -1.7359,  1.1830, -0.0266]])

In [7]:
x.view(16), x.view(-1,1)

(tensor([ 0.4078, -0.2062, -1.9476, -0.5783,  0.7319, -0.9079,  0.1607,  1.5403,
         -1.4357,  0.1099,  0.1589, -0.9753,  0.8379, -1.7359,  1.1830, -0.0266]),
 tensor([[ 0.4078],
         [-0.2062],
         [-1.9476],
         [-0.5783],
         [ 0.7319],
         [-0.9079],
         [ 0.1607],
         [ 1.5403],
         [-1.4357],
         [ 0.1099],
         [ 0.1589],
         [-0.9753],
         [ 0.8379],
         [-1.7359],
         [ 1.1830],
         [-0.0266]]))